version: '2'

services:
  homebridge:
    # https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Docker
    # https://github.com/homebridge/docker-homebridge
    # https://hub.docker.com/r/homebridge/homebridge
    image: homebridge/homebridge:2025-06-10
    network_mode: host
    volumes:
      - homebridge:/homebridge

volumes:
  homebridge: {}
